name: totally_clever
channels:
  - conda-forge
  - nodefaults
dependencies:
  - python=3.9
  - pytest=6.2
  - pylint=2.12
  - black=21.12b0
  - numpy=1.22.0
  - pip=22.0.3
  - pip:
    - arcade==2.6.10