name: totally_clever
channels:
  - conda-forge
  - nodefaults
dependencies:
  - python=3.9
  - pytest=6.2
  - pylint=2.12
  - black=22.3.0
  - numpy=1.22.0
  - pip=22.0.3
  - pillow=9.0.1
  - pip:
    - arcade==2.6.10
    - git+https://github.com/xietanu/pkg_arcade_sprite_ext.git@v0.1.0